version: '2'

services:
  kadira-engine:
    build: ./kadira-engine
    ports:
      - "11011:11011"
    environment:
      - PORT=11011
      - MONGO_URL=$KADIRA_MONGO_URL
      - MONGO_SHARD_URL_one=$KADIRA_MONGO_URL

  kadira-rma:
    build: ./kadira-rma
    environment:
      - MONGO_URL=$KADIRA_MONGO_URL

  kadira-ui:
    image: ulexus/meteor
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ROOT_URL=http://localhost:4000
      - MONGO_URL=$KADIRA_MONGO_URL
      - RELEASE=1.4.3.2
      - METEOR_SETTINGS={"public":{"tender":{"key":"405871e6-4816-4d44-a0f3-860c0e988078"},"intercom":{},"loginState":{"domain":"","cookieName":"kadira-dev-login-state"}},"tender":{"secret":"71825e70-d11d-489b-b273-2afdca024fd6"},"stripe":{"kadirahq":{"apiKey":"sk_test_22QITCBPhqEaEKjHXK5BBwO8","publishableKey":"pk_test_Tc1iVNRP9p8o7zgYWoWjZnm4","appName":"KadiraHQ","appLogo":"https://kadira.io/favicon.ico"}},"meteorDevelopers":{"clientId":"HcempmSyaawiyb4G4","secret":"snC3snsmTebC8HHCwwhqhHaAzAFxtFsQRL"}}
      - BUNDLE_FILE=/home/meteor/build.tar.gz
    volumes:
      - ./kadira-ui/kadira-ui.tar.gz:/home/meteor/build.tar.gz

