version: '2'

services:
  kadira-engine:
    build: ./kadira-engine
    ports:
      - "11011:11011"
    environment:
      - PORT=11011
      - MONGO_URL=$KADIRA_MONGO_URL
      - MONGO_SHARD_URL_one=$KADIRA_MONGO_URL

  kadira-rma:
    build: ./kadira-rma
    environment:
      - MONGO_URL=$KADIRA_MONGO_URL

  kadira-ui:
    image: ulexus/meteor
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ROOT_URL=http://localhost:4000
      - MONGO_URL=$KADIRA_MONGO_URL
      - MONGO_SHARD_URL_one=$KADIRA_MONGO_URL
      - RELEASE=1.4.3.2
      - BUNDLE_FILE=/home/meteor/build.tar.gz
    volumes:
      - ./kadira-ui/kadira-ui.tar.gz:/home/meteor/build.tar.gz

